Respect current port when redirecting search form POST to GET
MakairaIO/oxid-connect pull request #45
Opened 2023-03-30 11:02 UTC by mynetx

When running Oxid on a non-default webserver port (such as 8000), the search form will redirect to the default port (either 80 or 443), instead of respecting the current port.

2023-03-30 12:33 UTC, kyoya-de commented
Hello Joachim,
first of all thank you very much for your pull request.

I did a code review and found a small problem (details can be found in the review).


Greetings Stefan

2023-03-30 12:33 UTC, kyoya-de requested changes

2023-03-30 12:33 UTC, kyoya-de commented on src/oxid/core/makaira_connect_oxviewconfig.php
> +        $this->generatedFilterUrl[ $baseUrl ] = "{$parsedUrl['scheme']}://{$parsedUrl['host']}:{$parsedUrl['port']}{$path}{$query}";
The port should not be appended if it is a standard port. Among other things, this can cause HTTP requests to be sent to the HTTPS port and vice versa. It can also cause problems with the SSL/TLS certificate.
There is no check if the port is really necessary.

2023-03-30 15:34 UTC, mynetx commented on src/oxid/core/makaira_connect_oxviewconfig.php
> +        $this->generatedFilterUrl[ $baseUrl ] = "{$parsedUrl['scheme']}://{$parsedUrl['host']}:{$parsedUrl['port']}{$path}{$query}";
@kyoya-de I fixed that one. :)

2023-04-04 06:41 UTC, mynetx commented
@kyoya-de I can’t see your latest change request details.

2023-04-06 11:21 UTC, kyoya-de commented
Hello Joachim,

I am sorry that I did not have time to take care of the pull requests. Please use the branch `2.x` as target, this makes the porting to the other module versions easier for us. You may also need to rebase your branch to `2.x`.

Greetings Stefan

2023-04-06 12:29 UTC, mynetx commented
@kyoya-de I rebased the PR target and branch to `2.x`.

2023-04-06 13:05 UTC, kyoya-de approved these changes

2023-04-06 13:06 UTC, merged

2023-04-06 13:07 UTC, makaira-github commented
:tada: This PR is included in version 2.11.4 :tada:

The release is available on [GitHub release](https://github.com/MakairaIO/oxid-connect/releases/tag/2.11.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: